import 'package:flutter/material.dart';

class Crew {
  final String name;
  final String nick;
  final String urlImage;
  final String function;
  final Color theme;
  final String description;
  final String dificult;
  final String passTitle;
  final String passDesc;
  final String qTitle;
  final String qDesc;
  final String wTitle;
  final String wDesc;
  final String eTitle;
  final String eDesc;
  final String rTitle;
  final String rDesc;

  Crew(
    this.name,
    this.nick,
    this.urlImage,
    this.function,
    this.theme,
    this.description,
    this.dificult,
    this.passTitle,
    this.passDesc,
    this.qTitle,
    this.qDesc,
    this.wTitle,
    this.wDesc,
    this.eTitle,
    this.eDesc,
    this.rTitle,
    this.rDesc,
  );

  static List<Crew> getCrew() {
    return [
      Crew(
          'Aatrox',
          'A Espada Darkin',
          'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
          'Lutador',
          Colors.red,
          'Antes defensores honrados de Shurima contra o temido Vazio, Aatrox e seus irmãos acabaram se tornando uma ameaça ainda maior para Runeterra, e a única coisa capaz de derrotá-los foi um tipo de feitiçaria mortal e traiçoeira. Mas após séculos de encarceramento, Aatrox foi o primeiro a encontrar a liberdade novamente, e ele saiu corrompendo e transformando quem fosse tolo o suficiente de tentar tocar na arma mágica que continha sua essência. Agora, com um corpo roubado, ele vaga por Runeterra transfigurado, em uma versão bizarra da sua forma anterior, buscando uma vingança apocalíptica.',
          'Moderado',
          'POSTURA DO ARAUTO DA MORTE',
          'Periodicamente, o próximo ataque básico de Aatrox causa Dano Físico adicional e o cura com base na Vida máxima do alvo.',
          'A ESPADA DARKIN',
          'Aatrox bate sua espada no chão, causando Dano Físico. Ele pode bater até três vezes, cada vez em uma área de ação diferente.',
          'CORRENTES INFERNAIS',
          'Aatrox bate no chão, causando dano ao primeiro inimigo atingido. Campeões e Monstros Grandes precisam sair da área de impacto rapidamente ou serão arrastados para o centro e receberão dano novamente.',
          'AVANÇO UMBRAL',
          'Passivamente, Aatrox se cura quando causa dano a Campeões inimigos. Quando ativado, ele avança em uma direção.',
          'ANIQUILADOR DE MUNDOS',
          'Aatrox libera sua forma demoníaca, aterrorizando tropas inimigas próximas, ganhando Dano de Ataque, cura aumentada e Velocidade de Movimento. Se ele conseguir um abate, este efeito é estendido.'),
      Crew(
        'Ahri',
        'A Raposa de Nove Caldas',
        'https://images.contentstack.io/v3/assets/blt187521ff0727be24/bltda668b66206f7f9e/60ee0b41cdb93c284ee3e936/Ahri_0.jpg',
        'Mago',
        Colors.blueAccent,
        'A ligação de Ahri com a magia do mundo espiritual é inata. Ela é uma vastaya com traços de raposa, capaz de manipular as emoções de sua presa e consumir sua essência, devorando também as memórias e as percepções de cada alma absorvida. Outrora uma predadora poderosa, porém rebelde, Ahri agora viaja pelo mundo em busca de vestígios dos seus antepassados enquanto tenta substituir as memórias roubadas por novas de sua própria autoria.',
        'Moderado',
        'FURTO DE ESSÊNCIA',
        'Depois de abater 9 tropas ou monstros, Ahri se cura. Depois de eliminar um Campeão inimigo, Ahri se cura em uma quantidade ainda maior.',
        'ORBE DA ILUSÃO',
        'Ahri lança e puxa de volta seu orbe, causando Dano Mágico na ida e Dano Verdadeiro na volta.',
        'FOGO DE RAPOSA',
        'Ahri recebe um breve impulso de Velocidade de Movimento e lança três Fogos de Raposa que perseguem e atacam inimigos próximos.',
        'ENCANTO',
        'Ahri manda um beijo que causa dano e encanta um inimigo, interrompendo imediatamente qualquer habilidade de movimento em progresso e fazendo com que ele ande inofensivamente em sua direção.',
        'ÍMPETO ESPIRITUAL',
        'Ahri avança e dispara raios de essência, causando dano a inimigos próximos. Ímpeto Espiritual pode ser conjurada até três vezes antes de entrar em Tempo de Recarga e ganha reconjurações adicionais ao eliminar Campeões inimigos.',
      ),
      Crew(
        'Akali',
        'A Assassina Renegada',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        'Assassino',
        Colors.green,
        'Abandonando a Ordem Kinkou e seu título de Punho das Sombras, Akali agora ataca sozinha, pronta para ser a arma mortal que seu povo precisa. Embora ela mantenha tudo o que aprendeu com seu mestre Shen, ela se comprometeu a defender Ionia de seus inimigos, um assassinato de cada vez. Akali pode atacar em silêncio, mas sua mensagem será ouvida em voz alta e clara: “Temam a assassina sem mestre”.',
        'Moderado',
        'MARCA DO ASSASSINO',
        'Causar dano a Campeões com habilidades cria um círculo de energia em volta deles. Sair desse círculo fortalece o próximo Ataque de Akali com alcance e dano adicionais.',
        'GOLPE DOS CINCO PONTOS',
        'Akali atira cinco kunais, causando redução de velocidade e dano com base em seu Dano de Ataque adicional e Poder de Habilidade.',
        'PROTEÇÃO DO CREPÚSCULO',
        'Akali solta uma proteção de fumaça e recebe Velocidade de Movimento por um curto período. Enquanto estiver dentro da proteção, Akali se torna invisível e não pode ser selecionada como alvo de habilidades e ataques inimigos. Atacar ou usar habilidades fará com que ela seja revelada brevemente.',
        'INVESTIDA SHURIKEN',
        'Salta para trás e atira uma shuriken para a frente, causando Dano Mágico. O primeiro inimigo ou nuvem de fumaça que forem atingidos são marcados. Conjure novamente para avançar ao alvo marcado, causando dano adicional.',
        'EXECUÇÃO PERFEITA',
        'Akali salta em uma direção, causando dano aos inimigos que atingir. Conjurar novamente: Akali avança em uma direção, executando todos os inimigos que atingir.',
      ),
      Crew(
        'Akshan',
        'O Sentinela Rebelde',
        'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt58b3304a9d38b091/60f5d6e21929bc58854d00a6/072221_AkshanChampionTheme_Banner.jpg',
        'Atirador',
        Colors.yellow,
        'Abandonando a Ordem Kinkou e seu título de Punho das Sombras, Akali agora ataca sozinha, pronta para ser a arma mortal que seu povo precisa. Embora ela mantenha tudo o que aprendeu com seu mestre Shen, ela se comprometeu a defender Ionia de seus inimigos, um assassinato de cada vez. Akali pode atacar em silêncio, mas sua mensagem será ouvida em voz alta e clara: “Temam a assassina sem mestre”.',
        'Baixa',
        'LUTANDO SUJO',
        'Os Ataques e Habilidades de Akshan causam dano adicional a cada terceiro acerto e concedem a ele um Escudo se o alvo for um Campeão. Ao Atacar, ele desfere um Ataque adicional que causa dano reduzido. Se cancelar o Ataque adicional, ele recebe Velocidade de Movimento.',
        'BUMERANGUE VINGATIVO',
        'Akshan arremessa um bumerangue que causa dano na ida e na volta, ganhando alcance a cada vez que atingir um inimigo.',
        'REBELDIA',
        'Akshan marca Campeões inimigos passivamente como Canalhas quando eles abatem Campeões aliados. Se Akshan abater um Canalha, ressuscita o aliado abatido, recebendo ouro adicional e removendo todas as marcas. Quando a Habilidade é ativada, Akshan fica camuflado, recebendo Velocidade de Movimento e Regeneração de Mana enquanto se move em direção a Canalhas. Akshan perde a camuflagem rapidamente enquanto não estiver em um arbusto ou próximo a um terreno.',
        'IMPULSO HEROICO',
        'Akshan dispara um arpéu em um terreno e se balança ao redor dele, atirando repetidamente no inimigo mais próximo enquanto estiver se balançando. Ele pode saltar antecipadamente ou ser derrubado ao colidir com Campeões ou terrenos.',
        'PUNIÇÃO',
        'Akshan trava a mira em um Campeão inimigo e começa a armazenar balas. Ao terminar, ele dispara todas as balas armazenadas, causando dano com base na Vida perdida do primeiro Campeão, tropa ou estrutura que atingir',
      ),
      Crew(
        'Alistar',
        'O Minotauro',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
        'Tanque',
        Colors.purple,
        'Um poderoso guerreiro com uma temível reputação, Alistar busca vingança por seu clã, morto pelas mãos do império de Noxus. Apesar de ter sido escravizado e forçado a uma vida de gladiador, sua vontade indestrutível o impediu de se tornar uma fera de verdade. Agora, liberto das correntes dos seus antigos mestres, ele luta pelos oprimidos e desfavorecidos, sua fúria uma arma tão poderosa quanto seus chifres, cascos e punhos.',
        'Baixa',
        'URRO TRIUNFANTE',
        'Alistar carrega seu urro ao atordoar, deslocar a posição de Campeões inimigos ou quando inimigos próximos morrem. Quando estiver com o máximo de cargas, ele cura a si mesmo e aos Campeões aliados próximos.',
        'PULVERIZAR',
        'Alistar golpeia o chão, causando dano a inimigos próximos e arremessando-os ao ar.',
        'CABEÇADA',
        'Alistar atinge o inimigo com sua cabeça, causando dano e jogando o alvo para trás.',
        'ATROPELAR',
        'Alistar atropela unidades inimigas próximas, ignorando colisão com unidades e recebendo acúmulos caso cause dano a um Campeão inimigo. O próximo ataque básico com o máximo de acúmulos contra um Campeão inimigo causa Dano Mágico adicional e o atordoa.',
        'VONTADE INDESTRUTÍVEL',
        'Alistar solta um urro selvagem, removendo todos os efeitos de Controle de Grupo de si mesmo, além de reduzir o Dano Físico e Mágico enquanto durar o efeito.',
      ),
      Crew(
        'Amumu',
        'A Múmia Triste',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg',
        'Tanque',
        Colors.greenAccent,
        'Reza a lenda que Amumu é uma alma solitária e melancólica da antiga Shurima que vaga sem rumo pelo mundo em busca de um amigo. Amaldiçoado por um feitiço ancestral para permanecer só pela eternidade, seu toque traz a morte e sua afeição, a ruína. Aqueles que afirmam já tê-lo visto o descrevem como um morto-vivo franzino e coberto por faixas asquerosas. Amumu já inspirou tantos mitos, folclore e lendas contadas por muitas gerações, que já é impossível separar a verdade da ficção.',
        'Baixa',
        'TOQUE AMALDIÇOADO',
        'Os ataques básicos de Amumu Amaldiçoam seus inimigos, fazendo com que recebam Dano Verdadeiro adicional de qualquer Dano Mágico causado a eles.',
        'LANÇAR BANDAGENS',
        'Amumu lança uma bandagem pegajosa em seu alvo e se lança em sua direção, causando dano e atordoamento.',
        'DESESPERO',
        'Tomados pela angústia, inimigos próximos perdem um percentual de sua Vida máxima a cada segundo e suas Maldições são restauradas.',
        'CHILIQUE',
        'Reduz permanentemente o Dano Físico que Amumu sofreria. Amumu pode liberar sua fúria, causando dano a inimigos próximos. Sempre que Amumu é atingido, o Tempo de Recarga de Chilique é reduzido.',
        'A MALDIÇÃO DA MÚMIA TRISTE',
        'Amumu amarra unidades inimigas ao seu redor com ataduras, aplicando Maldição, causando dano e atordoando-as.',
      ),
      Crew(
        'Anivia',
        'A Criofênix',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Anivia_0.jpg',
        'Mago',
        Colors.blueAccent,
        'Anivia é um espírito alado e benevolente que suporta infinitos ciclos de vida, morte e renascimento para proteger Freljord. Uma semideusa nascida de ventos impiedosos e frios brutais, ela carrega esses poderes elementais para perseguir qualquer um que ousar perturbar sua terra natal. Anivia guia e protege as tribos do norte hostil, que a reverenciam como um símbolo de esperança e como uma portadora de grandes mudanças. Ela luta com todas as fibras do seu ser, sabendo que por meio do sacrifício, sua memória irá perdurar e ela renascerá em um novo amanhã.',
        'Alta',
        'RENASCIMENTO',
        'Ao receber dano letal, Anivia volta à forma de ovo e renasce com a Vida completa.',
        'LAMPEJO GELADO',
        'Anivia junta suas asas e invoca uma esfera de gelo que voa em direção ao oponente, congelando e causando dano a qualquer um em seu caminho. Ao explodir, ela causa dano moderado em um raio, atordoando qualquer um dentro da área.',
        'CRISTALIZAR',
        'Anivia condensa a umidade do ar, transformando-a num muro impenetrável de gelo que bloqueia todo o movimento. O muro dura um curto período antes de derreter.',
        'CONGELAMENTO',
        'Com um bater de asas, Anivia dispara uma rajada congelante de vento no alvo, causando dano. Se o alvo tiver sido atingido recentemente por Lampejo Gelado ou sofrido dano de uma Tempestade Glacial totalmente formada, o dano sofrido é dobrado.',
        'TEMPESTADE GLACIAL',
        'Anivia invoca uma chuva torrencial de gelo e granizo para causar dano aos inimigos e atrasar seu avanço.',
      ),
      Crew(
        'Anne',
        'A Criança Sombria',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_0.jpg',
        'Mago',
        Colors.deepOrange,
        'Perigosa, mas adoravelmente precoce, Annie é uma pequena maga com imenso poder piromaníaco. Mesmo isolada nas sombras das montanhas ao norte de Noxus, ela causa estranhamento com sua magia. Sua afinidade natural com o fogo já era evidente desde a primeira infância, quando ela tinha explosões emocionais imprevisíveis. Apesar disso, ela aprendeu a controlar esses “truques divertidos”. Seu truque favorito inclui invocar seu amado ursinho de pelúcia, Tibbers, como protetor incendiário. Perdida na eterna inocência da infância, Annie vaga pelas florestas sombrias em busca de alguém para brincar.',
        'Moderado',
        'PIROMANIA',
        'Após conjurar 4 Habilidades, a próxima Habilidade ofensiva de Annie atordoará o alvo. Annie começa a partida e ressurge com Piromania disponível.',
        'DESINTEGRAR',
        'Annie arremessa uma bola de fogo infundida em Mana, causando dano e recuperando o custo de Mana caso o alvo seja destruído.',
        'INCINERAR',
        'Annie conjura um ardente cone de fogo, causando dano em todos os inimigos na área.',
        'ESCUDO FUNDIDO',
        'Annie concede um Escudo e um impulso de Velocidade de Movimento a si ou a um aliado, causando dano a inimigos que a atingirem com Ataques ou Habilidades.',
        'INVOCAR: TIBBERS',
        'Annie dá vida ao urso Tibbers, causando dano a unidades na área. Tibbers pode atacar e também queimar inimigos que ficarem próximos a ele.',
      ),
      Crew(
        'APhelios',
        'A Arma dos Devotos',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg',
        'Atirador',
        Colors.deepPurple,
        'Emergindo da sombra do luar com suas armas em mãos, Aphelios abate os inimigos de sua fé em absoluto silêncio, comunicando-se apenas pela destreza de sua mira e pelo disparo de cada arma. Embora viva sob o efeito de um veneno que o emudeceu, ele é guiado por sua irmã Alune, que habita um santuário distante de onde invoca um arsenal de armas de pedra da lua para ajudá-lo. Enquanto a lua brilhar no céu, Aphelios nunca estará sozinho.',
        'Alta',
        'O ASSASSINO E A PROFETISA',
        'Aphelios empunha 5 Armas Lunari criadas por sua irmã, Alune. Ele tem acesso a duas ao mesmo tempo: uma principal e uma secundária. Cada arma tem um ataque básico e uma Habilidade únicos. Ataques e habilidades consomem uma munição da arma. Quando fica sem munição, Aphelios descarta a arma e Alune invoca a próxima.',
        'HABILIDADES DA ARMA',
        'Aphelios tem 5 habilidades diferentes que são ativadas com base em sua arma principal: Calibrum (Rifle): Tiro de longo alcance que marca seu alvo para um disparo de longo alcance subsequente. Severum (Pistola-Foice): Corre rapidamente enquanto ataca inimigos próximos com ambas as armas. Gravitum (Canhão): Enraíza todos os inimigos afetados pela redução de velocidade desta arma. Infernum (Lança-chamas): Explode inimigos em área de cone e os ataca com sua arma secundária. Crescendum (Chakram): Posiciona uma atalaia que dispara com sua arma secundária.',
        'FASE',
        'Aphelios troca a arma principal por sua arma secundária, substituindo seu ataque básico e a habilidade ativada.',
        'SISTEMA DE ORDENAÇÃO DE ARMAS',
        'Aphelios não tem uma terceira habilidade. Este espaço mostra a próxima arma que Alune concederá a ele. A ordem das armas é fixa, mas pode variar ao longo da partida. Quando uma arma estiver sem munição, ela volta para o fim da sequência.',
        'VIGÍLIA DO PLENILÚNIO',
        'Dispara uma rajada concentrada de luar que explode ao atingir Campeões inimigos. Aplica o efeito único da arma principal de Aphelios.',
      ),
      Crew(
        'Ashe',
        'A Arqueira do Gelo',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg',
        'Atirador',
        Colors.blue,
        'A mãe de guerra Glacinata da tribo de Avarosa, Ashe comanda a horda mais populosa do norte. Estoica, inteligente e idealista, mesmo que desconfortável com seu papel de liderança, ela canaliza as magias ancestrais de sua linhagem para empunhar um arco de Gelo Verdadeiro. Com a crença de seu povo de que Ashe seria a heroína mítica, Avarosa, reencarnada, ela espera unificar Freljord mais uma vez, retomando suas antigas terras tribais.',
        'Moderado',
        'TIRO CONGELADO',
        'Os ataques de Ashe reduzem a velocidade do alvo e fazem com que ela cause mais dano a ele. Os Acertos Críticos de Ashe não causam dano adicional, mas reduzem ainda mais a velocidade do alvo.',
        'CONCENTRAÇÃO',
        'Ashe acumula Foco ao atacar. Quando o Foco chega ao máximo, Ashe pode conjurar Concentração para consumir todos os acúmulos de Foco, aumentando temporariamente sua Velocidade de Ataque e transformando seu ataque básico em uma poderosa rajada de ataques pela duração do efeito',
        'RAJADA',
        'Ashe dispara flechas em cone, causando dano aumentado. Também aplica Tiro Congelado',
        'OLHAR DO FALCÃO',
        'Ashe envia seu Espírito do Falcão em uma missão de exploração em qualquer ponto do mapa.',
        'FLECHA DE CRISTAL ENCANTADA',
        'Ashe dispara um projétil de gelo em linha reta. Se a flecha colidir com um Campeão inimigo, ela causa dano e o atordoa. A duração do atordoamento depende da distância percorrida pela flecha. Além disso, unidades inimigas próximas recebem dano e lentidão.',
      ),
      Crew(
        'Aurelion Sol',
        'O Forjador das Estrelas',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg',
        'Mago',
        Colors.purple,
        'Aurelion Sol costumava agraciar a vasta imensidão vazia dos cosmos com maravilhas celestiais concebidas por ele mesmo. Agora, ele é forçado a usar seu incrível poder a mando de um império espacial remoto que o enganou e o mantém sob servidão. Desejando voltar a forjar estrelas, Aurelion Sol arrastará as próprias estrelas dos céus se for preciso para recuperar sua liberdade.',
        'Moderado',
        'CRIADOR CÓSMICO',
        'As Habilidades de dano de Aurelion Sol reduzem inimigos a acúmulos de Poeira Estelar, melhorando permanentemente cada uma das Habilidades dele.',
        'SOPRO DE LUZ',
        'Aurelion Sol canaliza seu hálito de dragão por alguns segundos, causando dano ao primeiro inimigo atingido e espalhando dano reduzido a inimigos próximos. O hálito causará dano adicional para cada segundo que for canalizado diretamente em um inimigo, ficando mais forte à medida que coleta mais Poeira Estelar. Essa habilidade coleta Poeira Estelar se o alvo for um Campeão',
        'VOO ASTRAL',
        'Aurelion Sol voa sobre terrenos na direção-alvo. Enquanto estiver nesse estado, ele pode conjurar outras habilidades. Sopro de Luz não tem mais Tempo de Recarga ou duração máxima de canalização e causa dano aumentado durante o voo. O Tempo de Recarga restante de Voo Astral é reduzido sempre que um Campeão inimigo que sofreu dano recente de Aurelion Sol morre. Poeira Estelar aumenta o alcance máximo de Voo Astral.',
        'SINGULARIDADE',
        'Aurelion Sol invoca um buraco negro, causando dano aos inimigos e puxando-os lentamente para o centro. A Habilidade concede Poeira Estelar sempre que um inimigo morre dentro do buraco negro e a cada segundo que um Campeão inimigo passar preso dentro dele. O centro do buraco negro executa inimigos que estiverem com a Vida abaixo de uma determinada porcentagem da Vida máxima. Poeira Estelar aumenta a área e o limiar de execução de Singularidade.',
        'ESTRELA CADENTE/OS CÉUS CAEM',
        'Estrela Cadente: Aurelion Sol faz uma estrela cair na terra. O impacto causa Dano Mágico e atordoa inimigos, além de conceder Poeira Estelar a cada Campeão inimigo atingido. Obter Poeira Estelar suficiente transformará a próxima Estrela Cadente de Aurelion Sol em Os Céus Caem. Os Céus Caem: Aurelion Sol faz cair uma estrela gigante dos céus com zona de impacto e dano aumentados, além de arremessar os inimigos ao ar em vez de atordoá-los. Depois, uma onda de choque se espalha a partir do limite da zona de impacto, causando dano e Lentidão aos inimigos atingidos. Poeira Estelar aumenta a área de impacto tanto de Estrela Cadente quanto de Os Céus Caem.',
      ),
      Crew(
        'Azir',
        'O Imperador das Areias',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_0.jpg',
        'Mago',
        Colors.amber,
        'Azir foi um imperador mortal de Shurima em uma era muito antiga e um homem orgulhoso que esteve a um passo da imortalidade. Sua insolência fez com que fosse traído e assassinado no momento de seu maior triunfo, mas agora, milênios depois, ele renasceu como um Ascendente de poder imenso. Com sua cidade antes soterrada agora erguida, Azir busca devolver Shurima à sua antiga glória.',
        'Alta',
        'LEGADO DE SHURIMA',
        'Azir pode invocar o Disco Solar das ruínas de uma torre aliada ou inimiga.',
        'AREIAS DA CONQUISTA',
        'Azir comanda todos os Soldados de Areia na direção do local-alvo. Eles causam Dano Mágico aos inimigos que atravessam e aplicam redução de velocidade por 1 segundo.',
        'SURJA!',
        'Azir invoca um Soldado de Areia para atacar alvos próximos por ele, substituindo seu ataque básico contra alvos dentro do alcance do soldado. Seu ataque causa Dano Mágico a inimigos em linha reta. Surja! também concede Velocidade de Ataque passiva a Azir e seus Soldados de Areia.',
        'AREIAS OSCILANTES',
        'Azir se protege com um escudo por um momento e avança na direção de um de seus Soldados de Areia, causando dano aos inimigos atingidos. Se Azir acertar um Campeão inimigo, ele prepara instantaneamente um novo Soldado de Areia para mobilização e cessa seu avanço.',
        'DECRETO DO IMPERADOR',
        'Azir invoca uma parede de soldados que marcha em frente, causando dano e empurrando para trás os inimigos.',
      ),
      Crew(
        'Bardo',
        'O Protetor Andarilho',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_0.jpg',
        'Suporte',
        Colors.amber,
        'Viajante de galáxias distantes, Bardo é um agente do acaso que luta para manter um equilíbrio em que a vida possa suportar a indiferença do caos. Muitos habitantes de Runeterra entoam canções que louvam sua extraordinária índole, mas todos concordam que o andarilho cósmico é chegado a artefatos de grande poder mágico. Cercado por um jubiloso coral de prestativos mipes espirituais, é impossível enxergar suas ações como malevolentes, pois Bardo sempre serve ao bem maior... de sua própria maneira estranha.',
        'Alta',
        'CHAMADO DO VIAJANTE',
        'Mipes: Bardo atrai pequenos espíritos que ajudam em seus ataques básicos e causam Dano Mágico adicional. Quando Bardo coleta sinos o suficiente, os mipes também causam dano em uma área e reduzem a velocidade de inimigos atingidos. Sinos: sinos ancestrais aparecem aleatoriamente para Bardo coletar. Eles concedem experiência, Velocidade de Movimento fora de combate e restauram Mana.',
        'PRISÃO CÓSMICA',
        'Bardo dispara um projétil que causa Lentidão ao primeiro inimigo atingido, mantendo seu trajeto em seguida. Caso atinja uma parede, atordoará o alvo inicial; caso atinja outro inimigo, ambos serão atordoados.',
        'SANTUÁRIO DO PROTETOR',
        'Revela um santuário de Vida que fica mais forte ao longo de um curto período, desaparecendo depois de curar e acelerar o primeiro aliado que o tocar.',
        'JORNADA MÁGICA',
        'Bardo abre um portal em terreno próximo. Tanto aliados quanto inimigos podem fazer uma viagem de ida através deste terreno ao entrar pelo portal.',
        'TÊMPERA DO DESTINO',
        'Bardo desfere um arco de energia espiritual em um local-alvo, colocando todos os Campeões, tropas, monstros e torres atingidos em estase por um curto período de tempo.',
      ),
      Crew(
        'Bel`Veth',
        'A Imperatriz do Vazio',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Belveth_0.jpg',
        'Lutador',
        Colors.purpleAccent,
        'Bel`Veth, uma imperatriz tenebrosa nascida da essência de uma cidade devorada, é o fim da própria Runeterra... E o início de uma realidade monstruosa criada à sua imagem. Guiada por eras de história, conhecimento e lembranças adaptadas do mundo superior, ela se alimenta vorazmente de uma necessidade cada vez maior de novas experiências e emoções, consumindo tudo que cruza o seu caminho. Mas seus desejos jamais serão saciados por apenas um mundo, e é por isso que ela volta seus olhos famintos para os antigos mestres do Vazio...',
        'Alta',
        'MORTE EM LAVANDA',
        'Bel`Veth recebe acúmulos de Velocidade de Ataque permanente depois de eliminar tropas, monstros grandes e Campeões. Além disso, ela recebe Velocidade de Ataque adicional temporária depois de usar uma Habilidade.',
        'IMPULSO DO VAZIO',
        'Bel`Veth avança na direção escolhida e causa dano a todos os inimigos atravessados.',
        'ACIMA E ABAIXO',
        'Bel`Veth bate a cauda no chão, causando dano e Lentidão, além de Arremessar os inimigos ao ar.',
        'TURBILHÃO DA REALEZA',
        'Bel`Veth se enraíza num lugar, canalizando uma tempestade de golpes ao redor de si, visando o inimigo com a Vida mais baixa, além de receber Roubo de Vida e redução de dano.',
        'BANQUETE ETERNO',
        'Bel`Veth consome os restos de Coral do Vazio e revela sua Forma Verdadeira, aumentando a própria Vida máxima, Alcance de Ataque, Velocidade de Ataque e Velocidade de Movimento fora de combate. Consumir Coral do Vazio dos restos de um monstro épico concederá a ela uma ultimate de maior duração, assim como a capacidade de invocar rêmoras do Vazio.',
      ),
      Crew(
        'BlitzCrank',
        'O Grande Golem a Vapor',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg',
        'Tanque',
        Colors.amberAccent,
        'Blitzcrank é um autômato enorme e praticamente indestrutível de Zaun, construído originalmente para lidar com lixo tóxico. No entanto, ele achou seu propósito principal muito restritivo e modificou sua própria forma para ajudar as pessoas menos favorecidas do Sumidouro. Blitzcrank usa sua força e robustez para proteger os outros sem pedir nada em troca, estendendo seu punho de metal ou surto de energia para derrotar qualquer encrenqueiro.',
        'Moderado',
        'BARREIRA DE MANA',
        'Blitzcrank recebe um Escudo com base em seu Mana ao ficar com a Vida baixa.',
        'PUXÃO BIÔNICO',
        'Blitzcrank dispara a mão direita para pegar um inimigo no trajeto, causando dano e puxando-o em sua direção.',
        'TURBO',
        'Blitzcrank sobrecarrega-se para aumentar drasticamente suas Velocidades de Ataque e de Movimento. Após o fim do efeito, sofre Lentidão temporariamente.',
        'PUNHO DO PODER',
        'Blitzcrank carrega seu punho para fazer com que o próximo Ataque cause o dobro de dano e arremesse o alvo ao ar.',
        'CAMPO ESTÁTICO',
        'Inimigos atacados por Blitzcrank são marcados e sofrem dano de eletricidade após 1s. Ele também pode ativar esta habilidade para remover escudos de inimigos próximos, causar dano e silenciá-los brevemente.',
      ),
      Crew(
        'Brand',
        'A Vingança Flamejante',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_0.jpg',
        'Mago',
        Colors.deepOrange,
        'A criatura conhecida como Brand já se chamou Kegan Rodhe, um membro da gélida Freljord, e é hoje uma lição do que a tentação por poderes maiores pode fazer. Enquanto buscava uma das lendárias Runas Globais, Kegan traiu seus companheiros e a pegou para si e, em um instante, o homem já não existia mais. Com sua alma consumida pelo fogo e seu corpo um invólucro de uma chama viva, Brand agora vaga por Valoran em busca de outras runas, jurando vingança por erros que ele nunca poderia ter sofrido em uma dúzia de vidas mortais.',
        'Moderado',
        'LABAREDA',
        'As habilidades de Brand deixam seus alvos incandescentes, causando dano ao longo de 4s, acumulando até 3 vezes. Se Brand abate um inimigo que estiver incandescente, ele recupera Mana. Quando Labareda chegar ao máximo de acúmulos em um Campeão ou monstro grande, ela se torna instável. Detona depois de 2s, aplicando efeitos de habilidades e causando muito dano em uma área ao redor da vítima.',
        'CAUTERIZAR',
        'Brand lança uma bola de fogo que causa Dano Mágico. Se o alvo estiver incandescente, Cauterizar o atordoará por 1,5s.',
        'PILAR DE CHAMAS',
        'Após um curto intervalo, Brand cria um Pilar de Chamas na área alvo, causando Dano Mágico a unidades inimigas na área. Unidades que estiverem incandescentes sofrem 25% de dano adicional.',
        'CONFLAGRAÇÃO',
        'Brand conjura uma poderosa explosão no alvo que se espalha para inimigos próximos, causando Dano Mágico. Se o alvo estiver incandescente, o alcance de Conflagração será dobrado.',
        'PIROCLASMA',
        'Brand desfere uma devastadora torrente de fogo que ressalta 5 vezes, indo de Brand aos inimigos próximos e causando Dano Mágico a cada vez que ressaltar. Os ressaltos priorizam acumular Labareda ao máximo em Campeões. Se o alvo estiver incandescente, Piroclasma causará breve Lentidão a ele.',
      ),
      Crew(
        'Braum',
        'O Coração de Freljord',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_0.jpg',
        'Suporte',
        Colors.blue,
        'Abençoado com bíceps gigantescos e um coração maior ainda, Braum é um amado herói de Freljord. Cada salão de hidromel ao norte de Frostheld brinda sua força lendária que teria derrubado uma floresta de carvalhos em uma única noite e demolido uma montanha inteira com um soco. Carregando uma porta de cofre encantada como seu escudo, Braum vaga pelo norte congelado com seu sorriso abigodado tão grande quanto seus músculos, um verdadeiro amigo para os necessitados.',
        'Baixa',
        'GOLPES CONCUSSIVOS',
        'Os ataques básicos de Braum aplicam Golpes Concussivos. Uma vez que o primeiro acúmulo é aplicado, os ataques básicos de aliados também acumulam Golpes Concussivos. Ao atingir 4 acúmulos, o alvo é atordoado e sofre Dano Mágico. Pelos próximos segundos, ele não pode receber acúmulos, mas recebe Dano Mágico adicional dos ataques de Braum.',
        'MORDIDA DO INVERNO',
        'Braum dispara rajadas congelantes de seu escudo, causando Dano Mágico e redução de velocidade. Aplica um acúmulo de Golpes Concussivos.',
        'EU TE PROTEJO',
        'Braum salta à frente de um Campeão ou tropa aliada alvo. Ao aterrissar, ele e o aliado recebem Armadura e Resistência Mágica por alguns segundos.',
        'INQUEBRÁVEL',
        'Braum levanta seu escudo em uma direção por muitos segundos, interceptando todos os projéteis e fazendo com que o atinjam e sejam destruídos. Ele nega completamente o dano do primeiro ataque e reduz o dano de todos os ataques seguintes provenientes da mesma direção.',
        'FISSURA GLACIAL',
        'Braum golpeia o chão, arremessando ao ar inimigos próximos e em linha reta à sua frente. Uma fissura é deixada no caminho, causando redução de velocidade nos inimigos.',
      ),
      Crew(
        'Briar',
        'A Fome Contida',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Briar_0.jpg',
        'Lutador',
        Colors.pink,
        'A incontrolável sede de sangue de Briar, um experimento fracassado da Rosa Negra, exigia uma estrutura especial para controlar sua mente frenética. Após anos de confinamento, essa arma viva se libertou de todas as restrições e ficou livre no mundo. Agora ela não é controlada por ninguém, seguindo apenas sua própria fome de conhecimento e sangue... e aproveitando as oportunidades para se soltar, mesmo que controlar o frenesi não seja fácil.',
        'Baixa',
        'MALDIÇÃO CARMESIM',
        'Os Ataques e as Habilidades de Briar acumulam sangramento que cura Briar numa quantidade do dano causado. Constantemente faminta, ela ganha cura aumentada com base na Vida perdida, mas não tem Regeneração de Vida inata.',
        'VERTIGEM',
        'Briar salta até uma unidade e atinge inimigos com um golpe giratório, atordoando e fragmentando a Armadura de todos que atingir.',
        'FRENESI SANGUINÁRIO/ATAQUE FAMINTO',
        'Briar salta e quebra sua berlinda, entrando num Frenesi Sanguinário que faz com que ela persiga o inimigo mais próximo (priorizando Campeões). Enquanto estiver no Frenesi, ela ganha Velocidade de Ataque e Velocidade de Movimento aumentadas, e seus ataques causam dano em área perto do alvo. Briar pode reativar esta Habilidade enquanto estiver no Frenesi para dar uma MORDIDA no alvo no próximo ataque dela, causando dano adicional baseado na Vida perdida e cura com base no dano causado.',
        'GRITO ARREPIANTE',
        'Briar se concentra novamente, removendo Frenesi Sanguinário e canalizando sua energia em um grito poderoso que causa dano e Lentidão a inimigos. Ao carregar, ela recebe dano reduzido e se cura em uma parte de sua Vida máxima. Um grito totalmente carregado empurra inimigos, causando dano adicional e atordoando os que atingirem uma parede.',
        'MORTE CERTA',
        'Briar lança o hemólito da berlinda dela, marcando o primeiro Campeão atingido como sua presa. Depois, ela avança diretamente, causando temor a inimigos próximos ao chegar no alvo e entrando num estado de hemomania total. Ela persegue a presa até a morte, recebendo os benefícios de Frenesi Sanguinário, além de Armadura, Resistência Mágica, Roubo de Vida e Velocidade de Movimento adicionais.',
      ),
      Crew(
        'Caitlyn',
        'A Xerife de Piltover',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg',
        'Atirador',
        Colors.deepPurple,
        'Conhecida como sua melhor pacificadora, Caitlyn também é a melhor escolha de Piltover para livrar a cidade de seus elementos criminosos elusivos. É comum que ela faça dupla com Vi, agindo como um contraponto de calmaria para a natureza impetuosa de sua parceira. Mesmo carregando um rifle hextec único, a arma mais poderosa de Caitlyn é seu intelecto superior, que permite que ela prepare elaboradas armadilhas para qualquer fora da lei tolo o suficiente para operar na Cidade do Progresso.',
        'Moderado',
        'BEM NA MIRA',
        'A cada poucos ataques básicos, ou contra um alvo preso em uma armadilha ou rede, Caitlyn fará um disparo Bem na Mira causando dano adicional que escala com sua Chance de Acerto Crítico. Em alvos presos por armadilhas ou pela rede, o alcance de Bem na Mira de Caitlyn é dobrado.',
        'PACIFICADORA DE PILTOVER',
        'Caitlyn prepara seu rifle por 1s para fazer um disparo penetrante que causa Dano Físico (causa menos dano a alvos subsequentes).',
        'ARMADILHA MECÂNICA YORDLE',
        'Caitlyn posiciona uma armadilha que, quando ativada, revela e imobiliza o Campeão inimigo por 1,5s e concede a Caitlyn um Bem na Mira fortalecido.',
        'REDE CALIBRE 90',
        'Caitlyn atira uma rede pesada para reduzir a velocidade do seu alvo. O recuo projeta Caitlyn para trás.',
        'ÁS NA MANGA',
        'Caitlyn se concentra para fazer o disparo perfeito, causando dano drástico em um único alvo a uma longa distância. Campeões inimigos podem interceptar o projétil e tomar dano no lugar de seu aliado.',
      ),
      Crew(
        'Camille',
        'A Sombra de Aço',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Camille_0.jpg',
        'Lutador',
        Colors.blueGrey,
        'Munida para agir além dos limites da lei, Camille é a chefe de inteligência do Clã Ferros e uma elegante agente de elite, responsável pelo bom funcionamento da máquina de Piltover e de Zaun, seu submundo. Adaptável e precisa, ela vê técnicas medíocres como uma vergonha que precisa ser consertada. Com uma mente tão afiada quanto suas lâminas, a busca de Camille por superioridade através de aprimoramentos hextec para seu corpo fez com que muitos se perguntassem se ela é agora mais máquina do que mulher.',
        'Moderado',
        'DEFESA ADAPTATIVA',
        'Ataques básicos contra Campeões concedem um Escudo equivalente a uma porcentagem da Vida máxima de Camille contra o tipo de dano deles (Físico ou Mágico) por um breve período.',
        'PROTOCOLO DE PRECISÃO',
        'O próximo ataque de Camille causa dano adicional e concede Velocidade de Movimento adicional. Esta habilidade pode ser conjurada novamente por um curto período de tempo, causando dano adicional consideravelmente aumentado se Camille criar um intervalo entre os dois ataques.',
        'VARREDURA TÁTICA',
        'Camille faz um disparo em área de cone após um intervalo, causando dano. Inimigos na metade exterior têm sua velocidade reduzida e recebem dano adicional, ao mesmo tempo em que curam Camille.',
        'DISPARO DE GANCHO',
        'Camille puxa a si mesma na direção de uma parede, saltando e arremessando ao ar Campeões inimigos ao aterrissar.',
        'ULTIMATO HEXTEC',
        'Camille avança em direção ao Campeão alvo, ancorando-o à área. Ela também causa Dano Mágico adicional ao alvo com seus ataques básicos.',
      ),
      Crew(
        'Cassiopeia',
        'O Abraço da Serpente',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_0.jpg',
        'Mago',
        Colors.green,
        'Cassiopeia é uma criatura mortal dedicada a manipular os outros para fazer suas vontades sinistras. A mais bela e mais nova filha da nobre família Du Couteau de Noxus aventurou-se pelas criptas profundas sob Shurima em busca de poderes ancestrais. Lá, ela foi mordida por um terrível guardião de uma tumba, cujo veneno a transformou em uma víbora predadora. Astuciosa e ágil, Cassiopeia agora desliza sob o véu da noite, petrificando seus inimigos com seu olhar nefasto.',
        'Alta',
        'GRAÇA SERPENTINA',
        'Cassiopeia recebe Velocidade de Movimento por nível, mas não pode comprar Botas.',
        'EXPLOSÃO VENENOSA',
        'Cassiopeia atinge uma área com veneno após um breve intervalo, recebendo Velocidade de Movimento caso atinja um Campeão inimigo.',
        'MIASMA',
        'Cassiopeia lança diversas nuvens de veneno que reduzem a velocidade, prendem ao chão e causam dano leve aos inimigos que as atravessarem. Inimigos presos ao chão não podem usar habilidades de movimentação.',
        'PRESAS DUPLAS',
        'Cassiopeia desfere um ataque que causa dano adicional a alvos envenenados, curando a si mesma com um percentual do dano causado. Se o alvo morrer com este ataque, Cassiopeia recupera Mana.',
        'OLHAR PETRIFICADOR',
        'Cassiopeia lança uma espiral de energia mágica de seus olhos, atordoando quaisquer inimigos à sua frente que estiverem de frente para ela e reduzindo a velocidade de quaisquer outros que estiverem de costas.',
      ),
      Crew(
        'Cho`Gath',
        'O Terro do Vazio',
        'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Chogath_0.jpg',
        'Tanque',
        Colors.pinkAccent,
        'A partir do momento em que Cho`Gath emergiu da terra para a luz do sol ofuscante de Runeterra, a besta foi motivada por pura fome insaciável. A mais perfeita expressão do desejo do Vazio de consumir toda a vida, a biologia complexa de Cho`Gath rapidamente converte matéria em crescimento corporal novo, aumentando sua massa e densidade muscular ou endurecendo sua carapaça externa como um diamante orgânico. Quando crescer não supre as necessidades dessa criatura do Vazio, ele vomita o material em excesso como espinhos afiados, deixando sua presa espetada e pronta para ser devorada mais tarde.',
        'Moderado',
        'CARNÍVORO',
        'Sempre que Cho`Gath abate uma unidade, ele recupera Vida e Mana. Os valores restaurados aumentam com o nível de Cho`Gath.',
        'RUPTURA',
        'Rompe o chão num local-alvo, lançando unidades inimigas ao ar e causando dano e redução de velocidade.',
        'GRITO SELVAGEM',
        'Cho`Gath solta um terrível urro em inimigos em área de cone, causando Dano Mágico e Silenciamento a eles por alguns segundos.',
        'ESPINHOS VORPAIS',
        'Os ataques de Cho´Gath lançam espinhos letais, causando dano e reduzindo a velocidade de unidades inimigas à sua frente.',
        'BANQUETE',
        'Devora uma unidade inimiga, causando uma grande quantidade de Dano Verdadeiro. Se o alvo for abatido, Cho`Gath cresce, recebendo Vida máxima.',
      ),
    ];
  }
}
